### PR TITLE
feat: implement PartialResultSetRead with resumes

### LINKED ISSUE #271: Implement resume support in Spanner Client
See the documentation for `resumeToken` for details: https://cloud.google.com/spanner/docs/reference/rest/v1/PartialResultSet

> Streaming calls might be interrupted for a variety of reasons, such as TCP connection loss. If this occurs, the stream of results can be resumed by re-sending the original request and including resumeToken. Note that executing any other transaction in the same session invalidates the token.

### LINKED ISSUE #674: Add retry/resume to internal::ConnectionImpl::Read
We need to:

- [x] Implement the functionality.
- [x] Write a unit test verifying that it tolerates at least one transient error.
- [x] Write a unit test verifying that it stops on the first permanent error.
- [x] Write a unit test verifying that it stops when there are too many transient failures.

### PR DESCRIPTION
**Pull request by coryan**
Use it in ConnectionImpl::Read to convince myself it is actually useful.

This fixes #271 and fixes #674

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/693)

### CODE REVIEW

**Comment by devbww** [comment]
> I am pretty sure you cannot capture member variables

This is true, but you can get the effect without the unnecessary incr/decr of the refcount by making `stub` a reference to `stub_`, and then capturing that by value.

**Comment by coryan** [comment]
That is a neat trick, done.

**Comment by devbww** [comment]
The comment is now somewhat misleading/confusing I think.

**Comment by coryan** [comment]
> The comment is now somewhat misleading/confusing I think.

I assume you mean the comment about `stub`.  I took another stab at it, if you still think it needs work please make a suggestion about what to say, or if you prefer we can remove it, I do not think it matters that much.

**Comment by devbww** [comment]
Sorry for not being more specific.  LGTM.  Thanks.

I'll defer the approval to @scotthart.

**Pull request merged**
