### PR TITLE
Change SessionHolder to return session as optional.

### PR DESCRIPTION
**Pull request by mr-salty**
This avoids assuming "empty" is "missing" as bww noted.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/474)

### CODE REVIEW

**Comment by remyabel** [comment]
> I think the current SessionHolder has the advantage of handling moves the way we'd like (the moved-from SessionHolder has no value) whereas an optional<SessionHolder> would still have a value which is a SessionHolder in some abnormal state.

Drive-by opinion: if `SessionHolder` is conceptually a `unique_ptr`, can we give it a `unique_ptr` member and invoke Rule of Zero?

**Comment by mr-salty** [comment]
@remyabel thanks - we discussed that some more and it might be the best option.  I put together #507 as an alternative to this PR.  Having to pass `unique_ptr<SessionHolder>` around is a little ugly but otherwise I think it's an improvement.

**Comment by coryan** [comment]
Should we review this PR or #507?

**Comment by devjgm** [comment]
Is this PR being dropped in favor of #507?

**Comment by devjgm** [comment]
> I think so, I was waiting for votes... so do you agree?
> 
> >

Yes. I think I like the unique_ptr change better.

**Comment by mr-salty** [comment]
closed in favor of #507

**Pull request closed without merging**
