### PR TITLE
fix: add missing call to google_cloud_cpp_spanner_deps

### PR DESCRIPTION
**Pull request by agasparovic-sabre**
Also update the version and use a working SHA256 in the example.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1215)

### CODE REVIEW

**Comment by agasparovic-sabre** [comment]
@googlebot I signed it!

**Comment by coryan** [comment]
@agasparovic-sabre thanks for sending these fixes, much appreciated.

**Comment by coryan** [comment]
And now I remembered, `INSTALL.md` is automatically generated from `ci/test-readme/generate-install.sh`.  Could you make the changes there too?

**Comment by coryan** [comment]
Thanks for the PR, as I mentioned above, this is an automatically generated file, so I fixed the generator instead in #1226.  I am going to close this PR.

**Comment by agasparovic-sabre** [comment]
Just saw this - @coryan thanks for the fix and great to connect again! :)

**Pull request closed without merging**
