### PR TITLE
chore: upgrade to google-cloud-cpp-common v0.18.0

### PR DESCRIPTION
**Pull request by devbww**
Also picks up the pending upgrade to protobuf v3.11.3.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1238)

### CODE REVIEW

**Comment by devbww** [comment]
As expected, the Windows builds are failing.

**Comment by coryan** [comment]
> It looks like vcpkg is involved, and that the errors are what I would expect from an old "common".
> 
> ```
> C:\PROGRA~2\MICROS~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe  /nologo /TP -DCARES_STATICLIB -D_WIN32_WINNT=0x600 -I..\ -I. -IT:\src\github\vcpkg\installed\x64-windows-static\include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MTd /Zi /Ob0 /Od /RTC1   /bigobj /std:c++latest /wd4996 /wd4244 /showIncludes /Fogoogle\cloud\bigtable\CMakeFiles\async_list_app_profiles_test.dir\async_list_app_profiles_test.cc.obj /Fdgoogle\cloud\bigtable\CMakeFiles\async_list_app_profiles_test.dir\ /FS -c ..\google\cloud\bigtable\async_list_app_profiles_test.cc
> ..\google\cloud\bigtable\async_list_app_profiles_test.cc(122): error C2661: 'google::cloud::grpc_utils::v0::internal::CompletionQueueImpl::SimulateCompletion': no overloaded function takes 1 arguments
> ```
> 
> etc.
> 
> > _[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp-spanner/1238#-:-M-GejqqEa4g_RM8jT9u:b-qkrgup)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @devjgm, @mr-salty, and @scotthart)

This is the link to the Windows+Bazel build:

https://source.cloud.google.com/results/invocations/922b8d6b-882c-42ad-a9c2-3e731aa2f02b

I see different errors

**Comment by coryan** [comment]
My first guess is that the code compiled with an old(er) version of Bazel.  The logs says 0.28.1, it is possible that this version does not work with the newer BUILD files for protobuf and/or gRPC. On Linux and macOS we test with Bazel >= 1.0.0, and I think we also do that in our workstations.

Updating Bazel on Windows requires a change like googleapis/google-cloud-cpp-common#154

**Comment by devbww** [comment]
For the record, the "Kokoro Windows CMake" failure is expected until we can make a consistent set of releases for vcpkg.

**Pull request merged**
